package com.pj109.xkorey.share.data;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pjos.proto

public final class SocketDataPro {
  private SocketDataPro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SocketDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SocketData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     */
    String getKey();
    /**
     * <code>string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string version = 2;</code>
     */
    String getVersion();
    /**
     * <code>string version = 2;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>repeated string event = 3;</code>
     */
    java.util.List<String>
        getEventList();
    /**
     * <code>repeated string event = 3;</code>
     */
    int getEventCount();
    /**
     * <code>repeated string event = 3;</code>
     */
    String getEvent(int index);
    /**
     * <code>repeated string event = 3;</code>
     */
    com.google.protobuf.ByteString
        getEventBytes(int index);

    /**
     * <code>bytes data = 4;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>.SocketData.DataType dataType = 5;</code>
     */
    int getDataTypeValue();
    /**
     * <code>.SocketData.DataType dataType = 5;</code>
     */
    SocketData.DataType getDataType();

    /**
     * <code>int32 echo = 6;</code>
     */
    int getEcho();
  }
  /**
   * Protobuf type {@code SocketData}
   */
  public  static final class SocketData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SocketData)
      SocketDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SocketData.newBuilder() to construct.
    private SocketData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SocketData() {
      key_ = "";
      version_ = "";
      event_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
      dataType_ = 0;
      echo_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SocketData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                event_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              event_.add(s);
              break;
            }
            case 34: {

              data_ = input.readBytes();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 48: {

              echo_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          event_ = event_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SocketDataPro.internal_static_SocketData_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SocketDataPro.internal_static_SocketData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SocketData.class, Builder.class);
    }

    /**
     * Protobuf enum {@code SocketData.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Str = 0;</code>
       */
      Str(0),
      /**
       * <code>Byt = 1;</code>
       */
      Byt(1),
      /**
       * <code>JStr = 2;</code>
       */
      JStr(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Str = 0;</code>
       */
      public static final int Str_VALUE = 0;
      /**
       * <code>Byt = 1;</code>
       */
      public static final int Byt_VALUE = 1;
      /**
       * <code>JStr = 2;</code>
       */
      public static final int JStr_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return Str;
          case 1: return Byt;
          case 2: return JStr;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return SocketData.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:SocketData.DataType)
    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private volatile Object key_;
    /**
     * <code>string key = 1;</code>
     */
    public String getKey() {
      Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private volatile Object version_;
    /**
     * <code>string version = 2;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList event_;
    /**
     * <code>repeated string event = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getEventList() {
      return event_;
    }
    /**
     * <code>repeated string event = 3;</code>
     */
    public int getEventCount() {
      return event_.size();
    }
    /**
     * <code>repeated string event = 3;</code>
     */
    public String getEvent(int index) {
      return event_.get(index);
    }
    /**
     * <code>repeated string event = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEventBytes(int index) {
      return event_.getByteString(index);
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 4;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int DATATYPE_FIELD_NUMBER = 5;
    private int dataType_;
    /**
     * <code>.SocketData.DataType dataType = 5;</code>
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.SocketData.DataType dataType = 5;</code>
     */
    public DataType getDataType() {
      @SuppressWarnings("deprecation")
      DataType result = DataType.valueOf(dataType_);
      return result == null ? DataType.UNRECOGNIZED : result;
    }

    public static final int ECHO_FIELD_NUMBER = 6;
    private int echo_;
    /**
     * <code>int32 echo = 6;</code>
     */
    public int getEcho() {
      return echo_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
      }
      for (int i = 0; i < event_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, event_.getRaw(i));
      }
      if (!data_.isEmpty()) {
        output.writeBytes(4, data_);
      }
      if (dataType_ != DataType.Str.getNumber()) {
        output.writeEnum(5, dataType_);
      }
      if (echo_ != 0) {
        output.writeInt32(6, echo_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < event_.size(); i++) {
          dataSize += computeStringSizeNoTag(event_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getEventList().size();
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      if (dataType_ != DataType.Str.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, dataType_);
      }
      if (echo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, echo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SocketData)) {
        return super.equals(obj);
      }
      SocketData other = (SocketData) obj;

      boolean result = true;
      result = result && getKey()
          .equals(other.getKey());
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && getEventList()
          .equals(other.getEventList());
      result = result && getData()
          .equals(other.getData());
      result = result && dataType_ == other.dataType_;
      result = result && (getEcho()
          == other.getEcho());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      if (getEventCount() > 0) {
        hash = (37 * hash) + EVENT_FIELD_NUMBER;
        hash = (53 * hash) + getEventList().hashCode();
      }
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      hash = (37 * hash) + ECHO_FIELD_NUMBER;
      hash = (53 * hash) + getEcho();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SocketData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SocketData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SocketData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SocketData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SocketData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SocketData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SocketData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SocketData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SocketData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SocketData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SocketData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SocketData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SocketData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SocketData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SocketData)
        SocketDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SocketDataPro.internal_static_SocketData_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SocketDataPro.internal_static_SocketData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SocketData.class, Builder.class);
      }

      // Construct using SocketDataPro.SocketData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        key_ = "";

        version_ = "";

        event_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;

        dataType_ = 0;

        echo_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SocketDataPro.internal_static_SocketData_descriptor;
      }

      @Override
      public SocketData getDefaultInstanceForType() {
        return SocketData.getDefaultInstance();
      }

      @Override
      public SocketData build() {
        SocketData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SocketData buildPartial() {
        SocketData result = new SocketData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.key_ = key_;
        result.version_ = version_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          event_ = event_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.event_ = event_;
        result.data_ = data_;
        result.dataType_ = dataType_;
        result.echo_ = echo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SocketData) {
          return mergeFrom((SocketData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SocketData other) {
        if (other == SocketData.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (!other.event_.isEmpty()) {
          if (event_.isEmpty()) {
            event_ = other.event_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureEventIsMutable();
            event_.addAll(other.event_);
          }
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        if (other.getEcho() != 0) {
          setEcho(other.getEcho());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SocketData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SocketData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object key_ = "";
      /**
       * <code>string key = 1;</code>
       */
      public String getKey() {
        Object ref = key_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private Object version_ = "";
      /**
       * <code>string version = 2;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList event_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureEventIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          event_ = new com.google.protobuf.LazyStringArrayList(event_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string event = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getEventList() {
        return event_.getUnmodifiableView();
      }
      /**
       * <code>repeated string event = 3;</code>
       */
      public int getEventCount() {
        return event_.size();
      }
      /**
       * <code>repeated string event = 3;</code>
       */
      public String getEvent(int index) {
        return event_.get(index);
      }
      /**
       * <code>repeated string event = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEventBytes(int index) {
        return event_.getByteString(index);
      }
      /**
       * <code>repeated string event = 3;</code>
       */
      public Builder setEvent(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEventIsMutable();
        event_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string event = 3;</code>
       */
      public Builder addEvent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEventIsMutable();
        event_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string event = 3;</code>
       */
      public Builder addAllEvent(
          Iterable<String> values) {
        ensureEventIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, event_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string event = 3;</code>
       */
      public Builder clearEvent() {
        event_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string event = 3;</code>
       */
      public Builder addEventBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureEventIsMutable();
        event_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 4;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 4;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 4;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int dataType_ = 0;
      /**
       * <code>.SocketData.DataType dataType = 5;</code>
       */
      public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <code>.SocketData.DataType dataType = 5;</code>
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.SocketData.DataType dataType = 5;</code>
       */
      public DataType getDataType() {
        @SuppressWarnings("deprecation")
        DataType result = DataType.valueOf(dataType_);
        return result == null ? DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.SocketData.DataType dataType = 5;</code>
       */
      public Builder setDataType(DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.SocketData.DataType dataType = 5;</code>
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private int echo_ ;
      /**
       * <code>int32 echo = 6;</code>
       */
      public int getEcho() {
        return echo_;
      }
      /**
       * <code>int32 echo = 6;</code>
       */
      public Builder setEcho(int value) {
        
        echo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 echo = 6;</code>
       */
      public Builder clearEcho() {
        
        echo_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SocketData)
    }

    // @@protoc_insertion_point(class_scope:SocketData)
    private static final SocketData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SocketData();
    }

    public static SocketData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SocketData>
        PARSER = new com.google.protobuf.AbstractParser<SocketData>() {
      @Override
      public SocketData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SocketData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SocketData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SocketData> getParserForType() {
      return PARSER;
    }

    @Override
    public SocketData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SocketData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SocketData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\npjos.proto\"\245\001\n\nSocketData\022\013\n\003key\030\001 \001(\t" +
      "\022\017\n\007version\030\002 \001(\t\022\r\n\005event\030\003 \003(\t\022\014\n\004data" +
      "\030\004 \001(\014\022&\n\010dataType\030\005 \001(\0162\024.SocketData.Da" +
      "taType\022\014\n\004echo\030\006 \001(\005\"&\n\010DataType\022\007\n\003Str\020" +
      "\000\022\007\n\003Byt\020\001\022\010\n\004JStr\020\002B\017B\rSocketDataProb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SocketData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SocketData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SocketData_descriptor,
        new String[] { "Key", "Version", "Event", "Data", "DataType", "Echo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
